name: NewsAgent nightly run

on:
  # every night at 05:00 UTC  (≈ 07:00 local Germany)
  schedule:
    - cron: '0 5 * * *'
  # manual “Run workflow” button
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣  checkout the code
    - uses: actions/checkout@v4

    # 2️⃣  set-up Python
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # 3️⃣  install Poetry + deps
    - name: Install dependencies (Poetry)
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-interaction --no-root

    # 4️⃣  run the NewsAgent
    - name: Run NewsAgent
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        SMTP_HOST:   ${{ secrets.SMTP_HOST }}
        SMTP_PORT:   ${{ secrets.SMTP_PORT }}
        SMTP_USER:   ${{ secrets.SMTP_USER }}
        SMTP_PASS:   ${{ secrets.SMTP_PASS }}
        RECIP_EN:    ${{ secrets.RECIP_EN }}
        RECIP_DE:    ${{ secrets.RECIP_DE }}
        RECIP_SV:    ${{ secrets.RECIP_SV }}
        RECIP_PL:    ${{ secrets.RECIP_PL }}
        SEND_EMAIL:  1           # or 0 to disable mailing
      run: |
        poetry run python -m src.newsagent.main \
          --channels data/channels.json \
          --threads 1 \
          --max-chunks 12
