name: NewsAgent nightly run

on:
  workflow_dispatch:      # ► manual “Run workflow” button
  schedule:               # ► every day at 05:00 UTC  (= ~07:00 CEST)
    - cron: '0 5 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:                  # ← pass the **repository secrets** to the job
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      SMTP_HOST:   ${{ secrets.SMTP_HOST }}
      SMTP_PORT:   ${{ secrets.SMTP_PORT }}
      SMTP_USER:   ${{ secrets.SMTP_USER }}
      SMTP_PASS:   ${{ secrets.SMTP_PASS }}
      RECIP_EN:    ${{ secrets.RECIP_EN }}
      RECIP_DE:    ${{ secrets.RECIP_DE }}
      RECIP_SV:    ${{ secrets.RECIP_SV }}
      RECIP_PL:    ${{ secrets.RECIP_PL }}
      SEND_EMAIL:  "1"               # <- treat “missing means 0”, so set it

    steps:
      # 1) grab your code
      - uses: actions/checkout@v4

      # 2) install Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'      # match your local version

      # 3) install dependencies
      #    • if you use Poetry, uncomment the “poetry” variant
      #    • otherwise keep the pip variant
      #
      # -- pip ----------------------------------------------------------
      - name: Install dependencies (pip)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      #
      # -- poetry -------------------------------------------------------
      # - uses: abatilo/actions-poetry@v3
      #   with:
      #     poetry-version: 1.8.2
      # - name: Install deps (poetry)
      #   run: poetry install --no-interaction --no-root
      # -----------------------------------------------------------------

      # 4) run NewsAgent
      - name: Run NewsAgent
        run: |
          python -m src.newsagent.main --channels data/channels.json --threads 1 --max-chunks 12

      # 5) (optional) upload the fresh reports as an artifact
      - name: Upload reports
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: newsagent-reports
          path: |
            src/reports/*.md
